/*
IONOS DBaaS MongoDB REST API

With IONOS Cloud Database as a Service, you have the ability to quickly set up and manage a MongoDB database. You can also delete clusters, manage backups and users via the API.  MongoDB is an open source, cross-platform, document-oriented database program. Classified as a NoSQL database program, it uses JSON-like documents with optional schemas.  The MongoDB API allows you to create additional database clusters or modify existing ones. Both tools, the Data Center Designer (DCD) and the API use the same concepts consistently and are well suited for smooth and intuitive use. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the PatchClusterProperties type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PatchClusterProperties{}

// PatchClusterProperties Properties of the payload to change a cluster.
type PatchClusterProperties struct {
	// The name of your cluster.
	DisplayName *string `json:"displayName,omitempty"`
	MaintenanceWindow *MaintenanceWindow `json:"maintenanceWindow,omitempty"`
	// The total number of instances in the cluster (one primary and n-1 secondaries). 
	Instances *int32 `json:"instances,omitempty"`
	Connections []Connection `json:"connections,omitempty"`
	// The unique ID of the template, which specifies the number of cores, storage size, and memory. You cannot downgrade to a smaller template or minor edition (e.g. from business to playground). To get a list of all templates to confirm the changes use the /templates endpoint. 
	TemplateID *string `json:"templateID,omitempty"`
}

// NewPatchClusterProperties instantiates a new PatchClusterProperties object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPatchClusterProperties() *PatchClusterProperties {
	this := PatchClusterProperties{}
	return &this
}

// NewPatchClusterPropertiesWithDefaults instantiates a new PatchClusterProperties object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPatchClusterPropertiesWithDefaults() *PatchClusterProperties {
	this := PatchClusterProperties{}
	return &this
}

// GetDisplayName returns the DisplayName field value if set, zero value otherwise.
func (o *PatchClusterProperties) GetDisplayName() string {
	if o == nil || IsNil(o.DisplayName) {
		var ret string
		return ret
	}
	return *o.DisplayName
}

// GetDisplayNameOk returns a tuple with the DisplayName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchClusterProperties) GetDisplayNameOk() (*string, bool) {
	if o == nil || IsNil(o.DisplayName) {
		return nil, false
	}
	return o.DisplayName, true
}

// HasDisplayName returns a boolean if a field has been set.
func (o *PatchClusterProperties) HasDisplayName() bool {
	if o != nil && !IsNil(o.DisplayName) {
		return true
	}

	return false
}

// SetDisplayName gets a reference to the given string and assigns it to the DisplayName field.
func (o *PatchClusterProperties) SetDisplayName(v string) {
	o.DisplayName = &v
}

// GetMaintenanceWindow returns the MaintenanceWindow field value if set, zero value otherwise.
func (o *PatchClusterProperties) GetMaintenanceWindow() MaintenanceWindow {
	if o == nil || IsNil(o.MaintenanceWindow) {
		var ret MaintenanceWindow
		return ret
	}
	return *o.MaintenanceWindow
}

// GetMaintenanceWindowOk returns a tuple with the MaintenanceWindow field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchClusterProperties) GetMaintenanceWindowOk() (*MaintenanceWindow, bool) {
	if o == nil || IsNil(o.MaintenanceWindow) {
		return nil, false
	}
	return o.MaintenanceWindow, true
}

// HasMaintenanceWindow returns a boolean if a field has been set.
func (o *PatchClusterProperties) HasMaintenanceWindow() bool {
	if o != nil && !IsNil(o.MaintenanceWindow) {
		return true
	}

	return false
}

// SetMaintenanceWindow gets a reference to the given MaintenanceWindow and assigns it to the MaintenanceWindow field.
func (o *PatchClusterProperties) SetMaintenanceWindow(v MaintenanceWindow) {
	o.MaintenanceWindow = &v
}

// GetInstances returns the Instances field value if set, zero value otherwise.
func (o *PatchClusterProperties) GetInstances() int32 {
	if o == nil || IsNil(o.Instances) {
		var ret int32
		return ret
	}
	return *o.Instances
}

// GetInstancesOk returns a tuple with the Instances field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchClusterProperties) GetInstancesOk() (*int32, bool) {
	if o == nil || IsNil(o.Instances) {
		return nil, false
	}
	return o.Instances, true
}

// HasInstances returns a boolean if a field has been set.
func (o *PatchClusterProperties) HasInstances() bool {
	if o != nil && !IsNil(o.Instances) {
		return true
	}

	return false
}

// SetInstances gets a reference to the given int32 and assigns it to the Instances field.
func (o *PatchClusterProperties) SetInstances(v int32) {
	o.Instances = &v
}

// GetConnections returns the Connections field value if set, zero value otherwise.
func (o *PatchClusterProperties) GetConnections() []Connection {
	if o == nil || IsNil(o.Connections) {
		var ret []Connection
		return ret
	}
	return o.Connections
}

// GetConnectionsOk returns a tuple with the Connections field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchClusterProperties) GetConnectionsOk() ([]Connection, bool) {
	if o == nil || IsNil(o.Connections) {
		return nil, false
	}
	return o.Connections, true
}

// HasConnections returns a boolean if a field has been set.
func (o *PatchClusterProperties) HasConnections() bool {
	if o != nil && !IsNil(o.Connections) {
		return true
	}

	return false
}

// SetConnections gets a reference to the given []Connection and assigns it to the Connections field.
func (o *PatchClusterProperties) SetConnections(v []Connection) {
	o.Connections = v
}

// GetTemplateID returns the TemplateID field value if set, zero value otherwise.
func (o *PatchClusterProperties) GetTemplateID() string {
	if o == nil || IsNil(o.TemplateID) {
		var ret string
		return ret
	}
	return *o.TemplateID
}

// GetTemplateIDOk returns a tuple with the TemplateID field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchClusterProperties) GetTemplateIDOk() (*string, bool) {
	if o == nil || IsNil(o.TemplateID) {
		return nil, false
	}
	return o.TemplateID, true
}

// HasTemplateID returns a boolean if a field has been set.
func (o *PatchClusterProperties) HasTemplateID() bool {
	if o != nil && !IsNil(o.TemplateID) {
		return true
	}

	return false
}

// SetTemplateID gets a reference to the given string and assigns it to the TemplateID field.
func (o *PatchClusterProperties) SetTemplateID(v string) {
	o.TemplateID = &v
}

func (o PatchClusterProperties) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PatchClusterProperties) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.DisplayName) {
		toSerialize["displayName"] = o.DisplayName
	}
	if !IsNil(o.MaintenanceWindow) {
		toSerialize["maintenanceWindow"] = o.MaintenanceWindow
	}
	if !IsNil(o.Instances) {
		toSerialize["instances"] = o.Instances
	}
	if !IsNil(o.Connections) {
		toSerialize["connections"] = o.Connections
	}
	if !IsNil(o.TemplateID) {
		toSerialize["templateID"] = o.TemplateID
	}
	return toSerialize, nil
}

type NullablePatchClusterProperties struct {
	value *PatchClusterProperties
	isSet bool
}

func (v NullablePatchClusterProperties) Get() *PatchClusterProperties {
	return v.value
}

func (v *NullablePatchClusterProperties) Set(val *PatchClusterProperties) {
	v.value = val
	v.isSet = true
}

func (v NullablePatchClusterProperties) IsSet() bool {
	return v.isSet
}

func (v *NullablePatchClusterProperties) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePatchClusterProperties(val *PatchClusterProperties) *NullablePatchClusterProperties {
	return &NullablePatchClusterProperties{value: val, isSet: true}
}

func (v NullablePatchClusterProperties) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePatchClusterProperties) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


